# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  # Build
  lane :itc do
    match(
      type: "appstore", 
      api_key_path: "./key.json",
      app_identifier: "kr.co.yongseongkim.Repeatit",
      force_for_new_devices: true
    )
    increment_build_number()
    build_app(
      scheme: "Repeatit",
      configuration: "Release",
      clean: true,
      output_directory: "./build/"
    )
    upload_to_testflight(
      api_key_path: "./key.json",
      app_identifier: "kr.co.yongseongkim.Repeatit",
      ipa: "./build/Repeatit.ipa",
      beta_app_description: "Repeatit for iOS",
      skip_waiting_for_build_processing: true
    )
  end
end
